- name: Re-deploy dev servers for fresh installation 
  hosts: "role_drupal:&env_dev{% if target_app is defined %}:&repo_{{ target_app }}{% endif %}"
  vars_files:
    - vault.yaml
  tasks:
    - name: Force Terraform to recreate this specific node
      delegate_to: terraform
      shell: |
        terraform apply -replace='proxmox_vm_qemu.proxmox_vms["{{ inventory_hostname }}"]' -auto-approve
      args:
        chdir: "/home/kevin/terraform"
      # Give the shell more time than the Terraform timeout
      async: 300 
      poll: 10
      throttle: 1