- name: Re-deploy dev servers for fresh installation
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  vars_files:
    - vault.yaml
  roles:
    - role: terraform_refresh
                                   