- name: Build Drupal centrally
  hosts: "role_drupal:&env_dev{% if target_app is defined %}:&repo_{{ target_app }}{% endif %}"
  gather_facts: false
  tasks:
    - name: Run the build role
      include_role:
        name: drupal_build
      run_once: true