- name: Build Drupal centrally
  hosts: "{{ target_app | default('role_drupal:&env_dev') }}"
  gather_facts: false
  tasks:
    - name: Run the build role
      include_role:
        name: drupal_build
      run_once: true