- name: Build Drupal centrally
  hosts: "role_drupal:&env_dev:&repo_{{ target_app | default('UNDEFINED') }}"
  gather_facts: false
  tasks:
    - name: Run the build role
      include_role:
        name: drupal_build
      run_once: true