- name: Parallel Deploy for Dev
  hosts: "{{ target_app | default('role_drupal:&env_dev') }}"
  vars_files:
    - vars.yaml
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml
  roles:
    - role: common_web      # Installs Apache, PHP, system tools
    - role: drupal_storage  # Handles NFS/Ceph mounts
    - role: drupal_app      # Syncs files, settings.php, themes
    - role: drupal_ops      # Runs Drush, restarts services