- name: Parallel Deploy for Dev
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  vars_files:
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml

  pre_tasks:
    - name: Set current_app fact for all roles
      ansible.builtin.set_fact:
        current_app: "{{ group_names | select('match', '^repo_') | first | replace('repo_', '') }}"

    - name: Verify build artifact exists
      include_tasks: tasks/check-build-dir.yaml
      vars: 
        target_repo_name: "{{ current_app }}"

  roles:
    - role: common_web      # Installs Apache, PHP, system tools
    - role: drupal_app      # Syncs files, settings.php, themes
    - role: drupal_storage  # Handles NFS/Ceph mounts
    - role: drupal_ops      # Runs Drush, restarts services