- name: Determine Drupal sites to Bake
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:
    - name: Identify target sites. If no repo provided, then use all of them.
      set_fact:
        app_list: >-
          {% if target_app is defined %}
            {{ [target_app] }}
          {% else %}
            {{ groups['role_drupal'] 
               | map('extract', hostvars, 'group_names') 
               | flatten 
               | select('match', '^repo_') 
               | map('replace', 'repo_', '') 
               | unique 
               | list }}
          {% endif %}

    - name: Ensure app_list is is a lists
      set_fact:
        app_list: "{{ app_list | from_yaml }}"

    - name: Ensure proxmox_nodes is a list
      set_fact:
        proxmox_nodes: "{{ groups['role_proxmox_host'] }}"

    - name: Display apps to be processed
      debug:
        msg: "The following apps will be baked: {{ app_list }}"

- name: Intiate loop for this app
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
    - vault.yaml
  vars:
    # Force these for any task in this play that delegates to Proxmox
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  tasks:
    - name: Loop through each identified app
      include_tasks: tasks/3a-bake-app-bridge.yaml
      loop: "{{ app_list }}"
      loop_control:
        loop_var: current_app