- name: Serial Rolling Deploy for Prod
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod"
  serial: 1  
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars_files:
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml
  tasks:
    # - name: Run terraform refresh on prod to overwrite from template
    #   include_role:
    #     name: terraform_refresh
    
    - name: Refresh database
      include_role:
        name: drupal_ops
      vars:
        target_repo: "{{ target_app }}"