- name: Determine Drupal sites to Deploy
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  tasks:
    - name: Identify target apps
      set_fact:
        app_list: >-
          {% if target_app is defined %}
            {{ [target_app] }}
          {% else %} 
            {{ groups['role_drupal'] 
               | map('extract', hostvars, 'group_names') 
               | flatten 
               | select('match', '^repo_') 
               | map('replace', 'repo_', '') 
               | unique 
               | list }}
          {% endif %}

    - name: Force app_list to be a list object
      set_fact:
        app_list: "{{ app_list | from_yaml }}"

- name: Serial Rolling Deploy for Prod
  hosts: "role_drupal:&env_prod{% if target_app is defined %}:&repo_{{ target_app }}{% endif %}"
  serial: 1  
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars_files:
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml
  tasks:
    - name: Clone and Configure Infrastructure
      include_tasks: tasks/4a-deploy-prod-images.yaml
      loop: "{{ hostvars['localhost']['app_list'] }}"
      loop_control:
        loop_var: current_app
      when: "'repo_' + current_app in group_names"

- name: Update DBs after deployment
  hosts: "role_drupal:&env_prod{% if target_app is defined %}:&repo_{{ target_app }}{% endif %}"
  vars_files:
    - vault.yaml
  tasks:
    - name: "Run Drupal Operations Role"
      include_role:
        name: drupal_ops
      vars:
        target_repo: "{{ current_app }}"
      loop: "{{ hostvars['localhost']['app_list'] }}"
      loop_control:
        loop_var: current_app
      when: "'repo_' + current_app in group_names"