- name: Serial Rolling Deploy for Prod
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod"
  serial: 1  
  tasks:
    - name: Run terraform refresh on prod to overwrite from template
      include_role:
        name: terraform_refresh

