- name: Bake Application Image
  hosts: localhost
  gather_facts: false
  vars_files:
    - vault.yaml
  
  pre_tasks:
    - name: Safety check - Ensure target_app is specified
      ansible.builtin.assert:
        that:
          - target_app is defined
          - target_app | length > 0
        fail_msg: "You must specify a site to bake. Example: -e 'target_app=nerdperk'"

- name: Serial Rolling Deploy for Prod
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_prod"
  serial: 1  
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  vars_files:
    - vault.yaml
    - /home/kevin/db-server/playbook/vault.yaml
  tasks:
    - name: Clone and Configure Infrastructure
      include_role:
        name: drupal_ops
      vars:
        target_repo: "{{ target_app }}"

    - name: Run terraform refresh on prod to overwrite from template
      include_role:
        name: terraform_refresh