plugin: netbox.netbox.nb_inventory
api_endpoint: http://netbox.thejfk.ca/
vars_files:
  - playbook/vault.yaml
token: "{{ lookup('ansible.builtin.unvault', 'playbook/vault.yaml') }}"
validate_certs: True
config_context: False

# This is the magic part: creating groups from custom fields
keyed_groups:
  # Creates groups like: repo_frontend, repo_database
  - prefix: repo
    key: custom_fields.repo
  # Creates groups like: env_dev, env_prod
  - prefix: env
    key: custom_fields.dev_or_prod