- name: Determine Drupal sites to Bake
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:
    - name: Identify target sites/repos by name. Returns a list
      import_tasks: tasks/identify-repos.yaml

    - name: Ensure proxmox_nodes is a list
      set_fact:
        proxmox_nodes: "{{ groups['role_proxmox_host'] }}"

    - name: Display apps to be processed
      debug:
        msg: "The following apps will be baked: {{ app_list }}"

- name: Intiate loop for this app
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml
    - vault.yaml
  tasks:
    - name: Loop through each identified app
      include_tasks: tasks/3a-bake-app-bridge.yaml
      loop: "{{ app_list }}"
      loop_control:
        loop_var: current_app